<?php

/*********************************************************************
* Extension configuration file for ext "robots".
*
* Generated by ext 17-02-2014 12:53 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Robot tags',
  'description' => 'Adds checkboxes for meta/robots tag on the page',
  'category' => 'fe',
  'author' => 'Dmitry Dulepov',
  'author_email' => 'dmitry.dulepov@gmail.com',
  'shy' => '',
  'dependencies' => '',
  'conflicts' => '',
  'priority' => '',
  'module' => '',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => 0,
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'author_company' => '',
  'version' => '1.0.1',
  'constraints' => 
  array (
    'depends' => 
    array (
      'php' => '5.3.2-5.5.99',
      'typo3' => '4.5.0-6.2.999',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  '_md5_values_when_last_written' => 'a:8:{s:9:"ChangeLog";s:4:"783d";s:28:"class.tx_robots_postproc.php";s:4:"c31a";s:12:"ext_icon.gif";s:4:"c800";s:17:"ext_localconf.php";s:4:"80a4";s:14:"ext_tables.php";s:4:"f3bf";s:14:"ext_tables.sql";s:4:"d047";s:16:"locallang_db.xml";s:4:"2103";s:14:"doc/manual.sxw";s:4:"e395";}',
  'suggests' => 
  array (
  ),
  'comment' => 'TYPO3 6.2 compatibility update',
  'user' => 'dmitry',
);

?>